spring:
  application:
    name: @pom.artifactId@
  datasource:    #默认配置了Hikari连接池，自动根据URL选择Driver
    url: jdbc:mysql://172.18.0.4:3306/microblog_resource
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://172.18.0.6:8080/.well-known/jwks.json
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
eureka:
  client:
    serviceURL:
      defaultZone: http://root:root@172.18.0.5:8761/eureka/    #服务注册中心集群
  instance:    #以下两个属性在开发环境下配置，不要在生产环境下配置
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #开启 数据库字段-驼峰式命名 映射
    lazy-loading-enabled: true    #开启懒加载

storage:    #自定义属性，用于配置文件存储的属性
  file-system:
    location: D:\software\Nginx\nginx-1.17.2\html\microblog
    host: http://localhost/
  ftp:
    url-prefix: http://192.168.1.100:10000/
    host: 192.168.1.100
    username: root
    password: root
