spring:
  application:
    name: @pom.artifactId@
eureka:
  client:
    serviceURL:
      defaultZone: http://root:root@172.18.0.5:8761/eureka/ #服务注册中心地址
  instance: #以下两个属性在开发环境下配置，不要在生产环境下配置
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
zuul:
  sensitive-headers:     #配置这个去掉默认的敏感头配置，防止把令牌过滤掉
# 上传大文件需要提高超时配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 126000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
